spring.application.name=analytics-service
server.port = 8081
spring.datasource.url=jdbc:postgresql://localhost:5432/analytics_db
spring.datasource.username = postgres
spring.datasource.password = ${password}