spring.application.name=analytics-service
server.port = 8081
spring.datasource.url=jdbc:postgresql://localhost:5432/analytics_db
spring.datasource.username = postgres
spring.datasource.password = ${password}

#this is used tell database to create tables when loading the programme if they are not available in database
spring.jpa.hibernate.ddl-auto = validate
#by this can see the sql queries run behind
spring.jpa.show-sql = true